POST http://localhost:5000/api/book/NewBook
Content-Type: application/json

{
    "title1": "Buồn",
    "author": "Kayle top 8",
    "rating":4.9,
    "language": "English",
    "description":"Như 1 định mệnh, Morgana và người chị gái của cô Kayle được sinh ra trong 1 thế giới đầy xung đột. Cuộc chiến tranh Cổ Ngữ tàn khốc lan ra khắp vùng Valoran và Shurima, và có chiều hướng lan ra đỉnh núi Targon xa xôi. Cha mẹ của Morgana, Mihira và Kilam, khi nghe về nguồn sức mạnh thần thánh nơi đỉnh ngọn núi vĩ đại - đã không còn lựa chọn nào khác ngoài tham gia vào một chuyến hành trình đằng đẵng và gian khổ, với hi vọng cứu rỗi bộ tộc của mình.Dù rằng MIhira đang mang thai trong người nhưng đôi vợ chồng vẫn không hề lùi bước. Cuối cùng khi Runeterra đã chạm đến thiên giới, Kilam đã vô cùng ngạc nhiên khi Mihira được lựa chọn làm vật chủ cho Thượng Nhân Công lý. Họ quay về bộ tộc với sức mạnh mà họ đã tìm thấy và sự ra đời cặp song sinh - Morgana và Kayle. Dù vậy, quyền năng thượng giới trong Mihira bắt đầu thay đổi con người phàm trần cũng như tình yêu thương của bà. Bà thường phó mặc hai đứa con gái cho người cha, và rời đi để đáp lại tiếng gọi của chiến trận.",
    "image":"https://img.wattpad.com/4b7c49778cb165f86b718916782fbb737ae53e2b/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f4941436155554138655a345551513d3d2d3837353730343038332e313630616136313635333931393335663734323436363734373938362e6a7067",
    "uri":"",
    "status":"false",
    "user":"Duy"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "luna1",
    "password" : "luna"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" : "luna1",
    "password" : "luna"
}

### 

POST http://localhost:5000/api/posts
Content-Type: application/json

{
  "title": "React",
  "description": "React",
  "url": "google.com",
  "status": "to learn"
}
###
GET http://localhost:5000/api/book/show
Content-Type: application/json

###
GET http://localhost:5000/api/book/show/downloaded
Content-Type: application/json

###
GET http://localhost:5000/api/book/autocomplete
Content-Type: application/json

###
POST  http://localhost:5000/api/book/download
Content-Type: application/json

{
    "title1":"Buồn"
}